<?php
function actormoviedb_page_attachments(array &$page){
  $page['#attached']['library'][] = 'actormoviedb/actormoviedb_pop_up';
}
function actormoviedb_theme($existing, $type, $theme, $path) {
  return array(
    'show_actor' => array(
      'variables' => array('actorList' => array(), 'title' => '',),
    ),
    'show_movie' => array(
      'variables' => array('movieList' => array(), 'title' => '',),
    ),
    'show_actor_movie' => array(
      'variables' => array('movieList' => array(),'title' => '',),
    ),
    'searchBox' => array(
      'render element' => 'form',
    ),
    'show_search' => array(
      'variables' => array('item' => array(), ),
    ),
    'form_block' => array(
      'variables' => array('title' => '', 'description' => '', 'image' => '',),
    ),
  );
}